# Generated by Django 4.2.16 on 2025-06-07 13:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('subject_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('sales', 'Sales Inquiry'), ('partnership', 'Partnership'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('donation_type', models.CharField(choices=[('one_time', 'One-time Donation'), ('monthly', 'Monthly Donation'), ('yearly', 'Yearly Donation'), ('project_based', 'Project-based Donation'), ('general', 'General Support')], default='one_time', max_length=20)),
                ('estimated_amount', models.CharField(blank=True, help_text="Rough estimate or range (e.g., '$100-500', 'Under $100')", max_length=50)),
                ('message', models.TextField(help_text='Tell us about your interest in supporting our cause')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=10)),
                ('best_contact_time', models.CharField(blank=True, help_text='When is the best time to reach you?', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('committed', 'Committed'), ('donated', 'Donated'), ('declined', 'Declined')], default='new', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for follow-up')),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('contact_attempts', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation Commitment',
                'verbose_name_plural': 'Donation Commitments',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
