# Generated by Django 5.2.1 on 2025-06-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0002_contact_donationcommitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcommitment',
            name='admin_notes',
            field=models.TextField(blank=True, default='No notes', help_text='Internal notes for follow-up'),
        ),
    ]
