# Generated by Django 5.2.1 on 2025-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0004_alter_donationcommitment_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('readed', 'Readed'), ('closed', 'Closed')], default='new', max_length=10),
        ),
    ]
