# Generated by Django 4.2.16 on 2026-08-25 08:38

from django.db import migrations, models
import django.db.models.deletion
import giftapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0006_galleryitem_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=giftapp.storage.LocalVideoStorage(), upload_to='gallery/videos/'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='giftapp.gallerycategory')),
                ('gallery_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='giftapp.galleryitem')),
            ],
        ),
    ]
