# Generated by Django 4.2.16 on 2026-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0008_uuid_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
